parameters:
    APP_ENV: '%env(APP_ENV)%'
    APP_SECRET: '%env(APP_SECRET)%'
    DATABASE_URL: '%env(DATABASE_URL)%'
    MAILER_URL: '%env(MAILER_URL)%'
    CONTACT_EMAIL: '%env(CONTACT_EMAIL)%'
    ADMIN_EMAIL: '%env(ADMIN_EMAIL)%'