parameters:
    APP_ENV: '%env(APP_ENV)%'
    APP_SECRET: '%env(APP_SECRET)%'
    DATABASE_URL: '%env(DATABASE_URL)%'
    MAILER_URL: '%env(MAILER_URL)%'
    CONTACT_EMAIL: '%env(CONTACT_EMAIL)%'
    ADMIN_EMAIL: '%env(ADMIN_EMAIL)%'
    CAN_CONFIRM_EVENT_AT: '%env(CAN_CONFIRM_EVENT_AT)%'
    SEND_REMAINDER_BY: '%env(SEND_REMAINDER_BY)%'
    MUST_CONFIRM_EVENT_BY: '%env(MUST_CONFIRM_EVENT_BY)%'
    REMAINDER_EMAIL_INTERVAL: '%env(REMAINDER_EMAIL_INTERVAL)%'