twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        ['form/bootstrap_4_layout.html.twig']
    globals:
        globals_register_fee: '%env(REGISTER_FEE)%'
        globals_yearly_fee: '%env(YEARLY_FEE)%'
        globals_free_period_days: '%env(FREE_PERIOD_DAYS)%'
        globals_theme_color_member: 'brown-background'
        globals_theme_color_organisation: 'blue-background'
        globals_theme_color_event_line: 'green-background'
        globals_theme_color_event: 'green2-background'
        globals_theme_color_person: 'red-background'
        globals_theme_color_error: 'red-background'
        globals_tawk_id: '%env(TAWK_ID)%'