checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: ["src/AppBundle/**/*"]

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false

tools:
    external_code_coverage: true