build:
  nodes:
    analysis:
      environment:
        node: 18
        php: 7.4
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths: ["src/*"]
  excluded_paths: ["src/Migrations/*"]

tools:
  external_code_coverage: true
