language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit
    - node_modules
    - vendor

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - COVERAGE=true
    - php: nightly
  allow_failures:
    - php: nightly

# prepare virtual environment
before_install:
  - if [[ $COVERAGE == false ]]; then phpenv config-rm xdebug.ini; fi

  # active node 12
  - nvm install v12

  # print versions just in case
  - php --version
  - node --version

# prepare programming environment
install:
  # copy config files
  - cp .env.test.travis .env.test
  - cp phpunit.xml.dist phpunit.xml

  # configure fontawesome
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_AUTH_TOKEN
  
  # install dependencies
  - composer install --no-scripts
  - yarn install
  - chmod +x ./bin/console

  # check if travis fulfills symfony requirements
  - php ./vendor/bin/requirements-checker

# prepare tests
before_script:
  # warmup cache to avoid excessive memory usage
  - php bin/console cache:warmup

  # init db & data
  - php bin/console doctrine:migrations:migrate -q
  - php bin/console doctrine:fixtures:load -q

  # init frontend
  - yarn encore production

# execute tests
script:
  # frontend vulnerability check
  - yarn audit

    # backend lint
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || ./vendor/bin/php-cs-fixer fix --diff --dry-run -v'
  - ./bin/console lint:yaml config
  - ./bin/console lint:yaml translations
  - ./bin/console lint:twig templates
  - composer validate --strict

  # backend vulnerability check
  - ./bin/console security:check

  # backend tests
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  - ./vendor/bin/phpunit

# report code coverage
after_script:
  # scrutinizer reporting
  - if [[ $COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi
