language: php

php:
    - 7.0
    - 7.1
    - nightly

matrix:
  allow_failures:
    - php: nightly

install:
    - composer install --dev

after_script:
  - ./vendor/bin/test-reporter
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
  - ./vendor/bin/codacycoverage clover ./build/logs/clover.xml
 
