<?php

/*
 * This file is part of the nodika project.
 *
 * (c) Florian Moser <git@famoser.ch>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Entity\Base\BaseEntity;
use App\Entity\Traits\EventTrait;
use App\Entity\Traits\IdTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * An EventGenerationPreviewEvent is an event generated by an EventGeneration.
 *
 * @ORM\Entity(")
 * @ORM\HasLifecycleCallbacks
 */
class EventGenerationPreviewEvent extends BaseEntity
{
    use IdTrait;
    use EventTrait;

    /**
     * @var EventGeneration|null
     *
     * @ORM\ManyToOne(targetEntity="EventGeneration", inversedBy="previewEvents")
     */
    private $generatedBy;

    public function getGeneratedBy(): ?EventGeneration
    {
        return $this->generatedBy;
    }

    public function setGeneratedBy(?EventGeneration $generatedBy): void
    {
        $this->generatedBy = $generatedBy;
    }
}
