<?php

namespace AppBundle\Repository;

/**
 * EventPastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPastRepository extends \Doctrine\ORM\EntityRepository
{
}
