<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Person;

/**
 * EventLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventLineRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMyEventLines(Person $person)
    {

    }
}
