<?php

namespace AppBundle\Repository;

/**
 * EventLineGenerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventLineGenerationRepository extends \Doctrine\ORM\EntityRepository
{
}
