<?php

namespace AppBundle\Repository;

/**
 * EventLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventLineRepository extends \Doctrine\ORM\EntityRepository
{
}
