<?php

namespace AppBundle\Repository;

/**
 * EventOfferEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventOfferEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
