<?php

namespace AppBundle\Repository;

/**
 * EventOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventOfferRepository extends \Doctrine\ORM\EntityRepository
{
}
