<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Member;
use AppBundle\Entity\Organisation;
use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{
    /**
     * @param Organisation $organisation
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getByOrganisationQueryBuilder(Organisation $organisation)
    {
        return $this->createQueryBuilder("u")->where('u.organisation = :organisation')->setParameter('organisation', $organisation);
    }

    /**
     * @param Organisation $organisation
     * @return Member[]
     */
    public function getIdAssociatedArray(Organisation $organisation)
    {
        $res = [];
        /* @var Member[] $members */
        $members = $this->findBy(["organisation" => $organisation]);
        foreach ($members as $memberEntry) {
            $res[$memberEntry->getId()] = $memberEntry;
        }
        return $res;
    }

    /**
     * @param Member $member
     * @return int
     */
    public function countUnassignedEvents(Member $member)
    {
        $qb = $this->createQueryBuilder('t');
        return $qb
            ->select('count(e.id)')
            ->join("t.events", "e")
            ->where($qb->expr()->isNull('e.person'))
            ->andWhere("t = :member")
            ->setParameter(":member", $member)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
