<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Event;
use AppBundle\Entity\Member;
use AppBundle\Entity\Organisation;
use AppBundle\Entity\Person;
use AppBundle\Enum\ApplicationEventType;
use AppBundle\Model\EventLine\EventLineModel;
use AppBundle\Model\Organisation\SetupStatusModel;

/**
 * OrganisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganisationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Organisation $organisation
     * @param \DateTime $dateTime
     * @param string $comparator
     * @param int $maxResults
     * @return Event[]
     */
    public function findEvents(Organisation $organisation, \DateTime $dateTime, $comparator = ">", $maxResults = 30)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select("e")
            ->from("AppBundle:Event", "e")
            ->join("e.member", "m")
            ->join("m.organisation", "o")
            ->where("e.startDateTime $comparator :startDateTime")
            ->andWhere("o = :organisation")
            ->setParameter('startDateTime', $dateTime)
            ->setParameter('organisation', $organisation)
            ->setMaxResults($maxResults)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param Organisation $organisation
     * @param \DateTime $dateTime
     * @param Member|null $filterMember
     * @param string $comparator
     * @param int $maxResults
     * @return EventLineModel[]
     */
    public function findEventLineModels(Organisation $organisation, \DateTime $dateTime, $filterMember = null, $comparator = ">", $maxResults = 30)
    {
        $res = [];
        foreach ($organisation->getEventLines() as $eventLine) {
            $eventLineModel = new EventLineModel();
            $eventLineModel->eventLine = $eventLine;
            $qb = $this->getEntityManager()->createQueryBuilder()
                ->select("e")
                ->from("AppBundle:Event", "e")
                ->join("e.eventLine", "el")
                ->leftJoin("e.member", "m")
                ->leftJoin("e.person", "p")
                ->where("e.endDateTime $comparator :startDateTime")
                ->andWhere("el = :eventLine");

            if ($filterMember instanceof Member) {
                $qb->andWhere("m = :member")
                    ->setParameter('member', $filterMember);
            }

            $qb->setParameter('startDateTime', $dateTime)
                ->setParameter('eventLine', $eventLine)
                ->setMaxResults($maxResults);

            $eventLineModel->events = $qb->getQuery()
                ->getResult();
            $res[] = $eventLineModel;
        }
        return $res;
    }

    /**
     * @param Person $person
     * @return array
     */
    public function findByPerson(Person $person)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select("o")
            ->from("AppBundle:Organisation", "o")
            ->join("o.members", "m")
            ->join("m.persons", "p")
            ->where("p = :person")
            ->setParameter('person', $person)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param Organisation $organisation
     * @return SetupStatusModel
     */
    public function getSetupStatus(Organisation $organisation)
    {
        $setupStatus = new SetupStatusModel();
        $setupStatus->setHasMembers($organisation->getMembers()->count() > 0);
        $setupStatus->setHasEventLines($organisation->getEventLines()->count() > 0);
        $hasEvents = false;
        foreach ($organisation->getEventLines() as $eventLine) {
            $hasEvents = $hasEvents || $eventLine->getEvents()->count() > 0;
        }
        $setupStatus->setHasEvents($hasEvents);
        $hasInvitedMembers = false;
        foreach ($organisation->getMembers() as $member) {
            $hasInvitedMembers = $hasInvitedMembers || $member->getHasBeenInvited();
        }
        $setupStatus->setHasInvitedMembers($hasInvitedMembers);
        $applicationEventRepo = $this->getEntityManager()->getRepository("AppBundle:ApplicationEvent");
        $hasVisitedSettings = $applicationEventRepo->hasEventOccurred($organisation, ApplicationEventType::VISITED_SETTINGS);
        $setupStatus->setHasVisitedSettings($hasVisitedSettings);
        return $setupStatus;
    }
}
