<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @return User|null
     */
    public function tryLogin(User $user)
    {
        /* @var User $tryUser */
        $tryUser = $this->findOneBy(["email" => $user->getEmail()]);
        $tryUser->setPlainPassword($user->getPlainPassword());
        if ($tryUser->tryLoginWithPlainPassword())
            return $tryUser;
        return null;
    }
}
