imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de

framework:
    #esi:             ~
    translator: { fallbacks: [de] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    form_themes:
            [":form:bootstrap_3_layout.html.twig"]
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      globals_register_fee: "%register_fee%"
      globals_yearly_fee: "%yearly_fee%"
      globals_free_period_days: "%free_period_days%"
      globals_color_class_member: "brown-background"
      globals_color_class_organisation: "blue-background"
      globals_color_class_event_line: "green-background"
      globals_color_class_event: "green2-background"
      globals_color_class_person: "red-background"
      globals_color_class_error: "red-background"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     "%database_path%"

    orm:
        default_entity_manager:  my_em
        auto_generate_proxy_classes:  "%kernel.debug%"
        entity_managers:
            # A collection of different named entity managers (e.g. some_em, another_em)
            my_em:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping:         true
                # Register SQL Filters in the entity manager
                filters:
                    # An array of filters
                    some_filter:
                        class:                AppBundle\Filter\DeleteFilter
                        enabled:              true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations