app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_administration:
    resource: "@AppBundle/Controller/Administration/"
    type:     annotation
    prefix:   /administration

app_administration_organisation:
    resource: "@AppBundle/Controller/Administration/Organisation"
    type:     annotation
    prefix:   /administration/organisation/{organisation}

app_administration_organisation_event_line:
    resource: "@AppBundle/Controller/Administration/Organisation/EventLine"
    type:     annotation
    prefix:   /administration/organisation/{organisation}/event_line/{eventLine}

app_administration_organisation_member:
    resource: "@AppBundle/Controller/Administration/Organisation/Member"
    type:     annotation
    prefix:   /administration/organisation/{organisation}/member/{member}

app_backend:
    resource: "@AppBundle/Controller/Backend/"
    type:     annotation
    prefix:   /backend

