services:
    admin.content.users:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: content, label: Benutzer }

    app.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: ["@doctrine"]