services:
    admin.content.users:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: content, label: Benutzer }

    app.frontend_user_provider:
        class: AppBundle\Security\FrontendUserProvider
        arguments: ["@doctrine"]

    app.admin_user_provider:
        class: AppBundle\Security\AdminUserProvider
        arguments: ["@doctrine", "%admin_emails%"]

    #voters
    app.voter.organisation:
        class:  AppBundle\Security\Voter\OrganisationVoter
        tags:
            - { name: security.voter }
        public: false

    #voters
    app.voter.event:
        class:  AppBundle\Security\Voter\EventVoter
        tags:
            - { name: security.voter }
        public: false

    #voters
    app.voter.event_line:
        class:  AppBundle\Security\Voter\EventLineVoter
        tags:
            - { name: security.voter }
        public: false

    app.exchange_service:
        class:  AppBundle\Service\ExchangeService
        arguments: ["@translator", "@session.flash_bag", "@validator", "@doctrine"]

    listener.entity.remove:
        class: AppBundle\Listener\DoctrinePreFlushListener
        tags:
            - { name: doctrine.event_listener, event: preFlush }