services:
    admin.content.users:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: content, label: Benutzer }

    app.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: ["@doctrine"]

    #voters
    app.voter.organisation:
        class:  AppBundle\Security\Voter\OrganisationVoter
        tags:
            - { name: security.voter }
        public: false

    app.exchange_service:
        class:  AppBundle\Service\ExchangeService
        arguments: ["@translator"]
