<?php

namespace App\Repository;

use App\Entity\FrontendUser;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrontendUserRepository extends EntityRepository
{
    /**
     * @param FrontendUser $user
     * @return FrontendUser|null
     */
    public function tryLogin(FrontendUser $user)
    {
        /* @var FrontendUser $tryUser */
        $tryUser = $this->findOneBy(["email" => $user->getEmail()]);
        $tryUser->setPlainPassword($user->getPlainPassword());
        if ($tryUser->tryLoginWithPlainPassword())
            return $tryUser;
        return null;
    }
}
