<?php

namespace App\Repository;

use App\Entity\Person;
use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    /**
     * @param Person $person
     * @param \DateTime $dateTime
     * @param string $comparator
     * @return array
     */
    public function getEventLinePreview(Person $person, \DateTime $dateTime, $comparator = ">")
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb->select("el")
            ->from("App:EventLine", "el")
            ->from("App:Event", "e")
            ->join("el.organisation", "o")
            ->join("o.members", "m")
            ->join("m.persons", "p")
            ->where("e.startDateTime $comparator :startDateTime")
            ->setParameter('startDateTime', $dateTime)
            ->setParameter("person", $person)
            ->getQuery()
            ->getResult();
    }
}
