<?php

/*
 * This file is part of the nodika project.
 *
 * (c) Florian Moser <git@famoser.ch>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Repository;

use App\Entity\Event;
use App\Entity\FrontendUser;
use App\Entity\Member;
use App\Entity\Settings;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * MemberRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends EntityRepository
{
    /**
     * @return Settings
     */
    public function findSingle()
    {
        $all = $this->findAll();
        if (count($all) > 0) {
            return $all[0];
        }
        return new Settings();
    }
}
