<?php

namespace App\Repository;

use App\Entity\FrontendUser;
use App\Entity\Setting;
use App\Enum\SettingKey;
use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends EntityRepository
{
    /**
     * @param FrontendUser $user
     * @param $settingKey
     * @return Setting|object
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function getByUser(FrontendUser $user, $settingKey)
    {
        $result = $this->findOneBy(["frontendUser" => $user->getId(), "key" => $settingKey]);
        if ($result != null) {
            return $result;
        }
        $result = new Setting();
        $result->setFrontendUser($user);
        $result->setKey($settingKey);
        $result->setContent(SettingKey::getDefaultContent($settingKey));

        $em = $this->getEntityManager();
        $em->persist($result);
        $em->flush();

        return $result;
    }
}
