<?php

/*
 * This file is part of the nodika project.
 *
 * (c) Florian Moser <git@famoser.ch>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Repository;

use App\Entity\FrontendUser;
use App\Entity\Setting;
use App\Enum\SettingKey;
use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends EntityRepository
{
    /**
     * @param FrontendUser $user
     * @param $settingKey
     *
     * @return Setting|object
     */
    public function getByUser(FrontendUser $user, $settingKey)
    {
        $result = $this->findOneBy(['frontendUser' => $user->getId(), 'key' => $settingKey]);
        if (null !== $result) {
            return $result;
        }
        $result = new Setting();
        $result->setFrontendUser($user);
        $result->setKey($settingKey);
        $result->setContent(SettingKey::getDefaultContent($settingKey));

        $em = $this->getEntityManager();
        try {
            $em->persist($result);
            $em->flush();
        } catch (\Exception $e) {
            //if it doesn't safe it to database we do not care so much, as its only settings affected
        }

        return $result;
    }
}
